version: '3.8'
services:
  app:
    build: .
    image: uploadfile-image
    container_name: uploadfile-container
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "9999:5000"
    restart: unless-stopped
